# Generated by Django 3.0 on 2021-06-06 09:03

from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=150)),
                ('productCategory', models.CharField(max_length=100)),
                ('productCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', mirage.fields.EncryptedCharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('accountStatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=150)),
                ('userole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.UserDetails')),
            ],
            options={
                'db_table': 'UserRoles',
            },
        ),
    ]
